//! macOS capture and paste: NSPasteboard for reading and writing, CGEvent for ⌘V, and the
//! Vision framework for text in images.

use objc2::AnyThread;
use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{
    NSBitmapImageFileType, NSBitmapImageRep, NSPasteboard, NSPasteboardWriting, NSWorkspace,
};
use objc2_foundation::{NSArray, NSData, NSDictionary, NSString, NSURL};

use super::{Capture, Content, Platform};

pub struct MacClipboard;

// The nspasteboard.org markers apps set on what shouldn't be kept.
const SKIP_MARKERS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
];

const FILE_URL: &str = "public.file-url";
const PLAIN_TEXT: &str = "public.utf8-plain-text";
const PNG: &str = "public.png";
const TIFF: &str = "public.tiff";

/// Kept small: a huge image would make every list and save slow.
const MAX_IMAGE_BYTES: usize = 25 << 20;

#[link(name = "ApplicationServices", kind = "framework")]
unsafe extern "C" {
    fn AXIsProcessTrusted() -> bool;
    fn AXIsProcessTrustedWithOptions(options: *const std::ffi::c_void) -> bool;
    static kAXTrustedCheckOptionPrompt: *const std::ffi::c_void;
}

fn has_type(types: &NSArray<NSString>, wanted: &str) -> bool {
    types.iter().any(|kind| kind.to_string() == wanted)
}

fn frontmost() -> Option<(String, String)> {
    let app = NSWorkspace::sharedWorkspace().frontmostApplication()?;
    let name = app.localizedName().map(|name| name.to_string())?;
    let id = app
        .bundleIdentifier()
        .map(|id| id.to_string())
        .unwrap_or_else(|| app.processIdentifier().to_string());
    Some((name, id))
}

fn png_from(data: &NSData) -> Option<(Vec<u8>, u32, u32)> {
    let rep = NSBitmapImageRep::imageRepWithData(data)?;
    let width = rep.pixelsWide().max(0) as u32;
    let height = rep.pixelsHigh().max(0) as u32;
    let png = unsafe {
        rep.representationUsingType_properties(NSBitmapImageFileType::PNG, &NSDictionary::new())
    }?;
    Some((png.to_vec(), width, height))
}

impl Platform for MacClipboard {
    fn change_count(&self) -> i64 {
        NSPasteboard::generalPasteboard().changeCount() as i64
    }

    fn read(&self) -> Option<Capture> {
        let board = NSPasteboard::generalPasteboard();
        let types = board.types()?;
        if SKIP_MARKERS.iter().any(|marker| has_type(&types, marker)) {
            return None;
        }
        let source = frontmost();

        if has_type(&types, FILE_URL) {
            let files: Vec<String> = board
                .pasteboardItems()
                .into_iter()
                .flat_map(|items| items.iter().collect::<Vec<_>>())
                .filter_map(|item| item.stringForType(&NSString::from_str(FILE_URL)))
                .filter_map(|url| NSURL::URLWithString(&url))
                .filter_map(|url| url.path().map(|path| path.to_string()))
                .collect();
            if !files.is_empty() {
                return Some(Capture {
                    content: Content::Files(files),
                    source,
                });
            }
        }

        // Prefer text when an app offers both (a spreadsheet cell copies as text and an image).
        if let Some(text) = board.stringForType(&NSString::from_str(PLAIN_TEXT)) {
            let text = text.to_string();
            if !text.trim().is_empty() {
                return Some(Capture {
                    content: Content::Text(text),
                    source,
                });
            }
        }

        let data = board
            .dataForType(&NSString::from_str(PNG))
            .or_else(|| board.dataForType(&NSString::from_str(TIFF)))?;
        if data.len() > MAX_IMAGE_BYTES {
            return None;
        }
        let (png, width, height) = png_from(&data)?;
        Some(Capture {
            content: Content::Image { png, width, height },
            source,
        })
    }

    fn write(&self, content: &Content, plain: bool) -> Result<(), String> {
        let board = NSPasteboard::generalPasteboard();
        board.clearContents();
        let written = match content {
            Content::Text(text) => {
                board.setString_forType(&NSString::from_str(text), &NSString::from_str(PLAIN_TEXT))
            }
            Content::Files(paths) if plain => board.setString_forType(
                &NSString::from_str(&paths.join("\n")),
                &NSString::from_str(PLAIN_TEXT),
            ),
            Content::Files(paths) => {
                let urls: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = paths
                    .iter()
                    .map(|path| {
                        ProtocolObject::from_retained(NSURL::fileURLWithPath(&NSString::from_str(
                            path,
                        )))
                    })
                    .collect();
                board.writeObjects(&NSArray::from_retained_slice(&urls))
            }
            Content::Image { png, .. } => {
                board.setData_forType(Some(&NSData::with_bytes(png)), &NSString::from_str(PNG))
            }
        };
        if written {
            Ok(())
        } else {
            Err("Couldn't put that on the clipboard".into())
        }
    }

    fn can_paste(&self, prompt: bool) -> bool {
        unsafe {
            if !prompt {
                return AXIsProcessTrusted();
            }
            let key: &objc2_foundation::NSString = &*(kAXTrustedCheckOptionPrompt.cast());
            let yes = objc2_foundation::NSNumber::new_bool(true);
            let options = NSDictionary::from_slices(&[key], &[&*yes]);
            AXIsProcessTrustedWithOptions(Retained::as_ptr(&options).cast())
        }
    }

    fn send_paste(&self) -> Result<(), String> {
        use objc2_core_graphics::{CGEvent, CGEventFlags, CGEventTapLocation};
        const V_KEY: u16 = 9;
        for down in [true, false] {
            let event = CGEvent::new_keyboard_event(None, V_KEY, down)
                .ok_or("Couldn't create the paste keystroke")?;
            CGEvent::set_flags(Some(&event), CGEventFlags::MaskCommand);
            CGEvent::post(CGEventTapLocation::HIDEventTap, Some(&event));
        }
        Ok(())
    }

    fn recognize_text(&self, png: &[u8]) -> Option<String> {
        use objc2_vision::{
            VNImageRequestHandler, VNRecognizeTextRequest, VNRequest, VNRequestTextRecognitionLevel,
        };
        objc2::rc::autoreleasepool(|_| {
            let data = NSData::with_bytes(png);
            let handler = VNImageRequestHandler::initWithData_options(
                VNImageRequestHandler::alloc(),
                &data,
                &NSDictionary::new(),
            );
            let request = VNRecognizeTextRequest::new();
            request.setRecognitionLevel(VNRequestTextRecognitionLevel::Accurate);
            request.setUsesLanguageCorrection(true);
            let as_request: Retained<VNRequest> =
                Retained::into_super(Retained::into_super(request.clone()));
            handler
                .performRequests_error(&NSArray::from_retained_slice(&[as_request]))
                .ok()?;
            let lines: Vec<String> = request
                .results()?
                .iter()
                .filter_map(|observation| {
                    observation
                        .topCandidates(1)
                        .firstObject()
                        .map(|candidate| candidate.string().to_string())
                })
                .collect();
            let text = lines.join("\n");
            (!text.trim().is_empty()).then_some(text)
        })
    }
}
